src/Entity/Brand.php
<?php

namespace App\Entity;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\BrandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\HasLifecycleCallbacks]
#[UniqueEntity('name')]
#[ORM\Entity(repositoryClass: BrandRepository::class)]
class Brand
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 100,
        minMessage: 'Le nom doit avoir au moins {{ limit }} caractères.',
        maxMessage: 'Le nom ne doit pas dépasser {{ limit }} caractères.',
    )]
    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[Assert\NotBlank]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\OneToMany(mappedBy: 'brand', targetEntity: Model::class, orphanRemoval: true)]
    private Collection $models;

    public function __construct()
    {
        $this->models = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return Collection<int, Model>
     */
    public function getModels(): Collection
    {
        return $this->models;
    }

    public function addModel(Model $model): static
    {
        if (!$this->models->contains($model)) {
            $this->models->add($model);
            $model->setBrand($this);
        }

        return $this;
    }

    public function removeModel(Model $model): static
    {
        if ($this->models->removeElement($model)) {
            // set the owning side to null (unless already changed)
            if ($model->getBrand() === $this) {
                $model->setBrand(null);
            }
        }

        return $this;
    }

    #[ORM\PostRemove]
    public function deleteLogo()
    {
        if ($this->logo != null) {
            unlink(__DIR__.'/../../public/uploads/'.$this->logo);
        }
        return true; 
    }
}

src/Form/BrandType.php
<?php

namespace App\Form;

use App\Entity\Brand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class BrandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('created_at')
            ->add('logo', FileType::class, [
                'label' => 'Logo (jpg, png)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using attributes
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid logo.',
                    ])
                ],
            ])
            ->add('enregistrer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Brand::class,
        ]);
    }
}

src/Controller/BrandController.php
<?php

namespace App\Controller;

use App\Entity\Brand;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\BrandType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[Route('/{_locale}/marques')]
class BrandController extends AbstractController
{
    /**
     * List of the brands & create form
     */
    #[Route('/', name: 'app_brands')]
    public function brands(EntityManagerInterface $em, Request $request): Response
    {
        // Create a new brand
        $brand = new Brand(); 
        $form = $this->createForm(BrandType::class, $brand); 
        $form->handleRequest($request); 
        if ($form->isSubmitted() && $form->isValid()) {
            // Upload a logo image
            $imageFile = $form->get('logo')->getData();
            if ($imageFile) {
                $newFilename = uniqid().'.'.$imageFile->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $imageFile->move(
                        $this->getParameter('upload_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Impossible d\'ajouter le logo.'); 
                }
                $brand->setLogo($newFilename);
            }

            $em->persist($brand); 
            $em->flush(); 

            $this->addFlash(
                'success',
                'Nouvelle marque créée!'
            );
        }

        // Get all the brands in the database 
        $brands = $em->getRepository(Brand::class)->findAll();  

        return $this->render('brand/brands.html.twig', [
            'brands' => $brands,
            'add_form' => $form->createView(),
        ]);
    }

    /**
     * Detail of a brand and update a brand
     */
    #[Route('/{id}', name: 'app_brand')]
    public function brand(EntityManagerInterface $em, Brand $brand = null, Request $request): Response
    {
        // Check if the beand exists
        if ($brand == null) {
            $this->addFlash(
                'danger',
                'Marque introuvable!'
            );
            return $this->redirectToRoute('app_brands'); 
        } 
 
        // Update form
        $form = $this->createForm(BrandType::class, $brand); 
        $form->handleRequest($request); 
        if ($form->isSubmitted() && $form->isValid()) {
            // Edit the logo
            $imageFile = $form->get('logo')->getData();
            if ($imageFile) {
                $newFilename = uniqid().'.'.$imageFile->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $imageFile->move(
                        $this->getParameter('upload_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Impossible d\'ajouter le logo.'); 
                }
                $brand->setLogo($newFilename);
            }

            $em->persist($brand); 
            $em->flush(); 
            $this->addFlash(
                'success',
                'La marque a bien été modifiée!'
            );
        }
  
        return $this->render('brand/brand.html.twig', [
            'brand' => $brand, 
            'update' => $form->createView(),
        ]);
    }

    /**
     * Delete a brand
     */
    #[Route('/delete/{id}', name: 'delete_brand')]
    public function delete(EntityManagerInterface $em, Brand $brand = null): RedirectResponse
    {
        if ($brand == null) {
            $this->addFlash(
                'danger',
                'Marque introuvable!'
            );
            return $this->redirectToRoute('app_brands'); 
        }

        // Remove the brand 
        $em->remove($brand); //Prepare sauvg
        $em->flush(); 
        $this->addFlash(
            'warning',
            'Marque supprimée!'
        );
        return $this->redirectToRoute('app_brands'); 
    }
}

templates/brand/brand.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une marque{% endblock %}

{% block body %}
    <section class="title">
		<h1 class=" text-center">{{ brand.name }}</h1>
        <p class=" text-center">Créée le {{ brand.createdAt|date("m/d/Y") }}</p>
	</section>

    {# Update form for a brand #}
    <section class="update-form my-4">
        <div class="row d-flex justify-content-center">
            <div class="col-12 border p-3 rounded">
                <h2 class="text-center" style="font-size:24px;">Modifier une marque</h2>
                {{ form(update) }}  
            </div>
        </div>
    </section>

{% endblock %}

templates/brand/brands.html.twig
{% extends 'base.html.twig' %}

{% block title %} Marques {% endblock %}

{% block body %}
	<section class="title">
		<h1 class=" text-center">Les marques</h1>
	</section>

	<section class="list ">
        {# List of the brands #}
        {% if brands is not empty %}
		<table class="table table-striped border my-3">
			<thead>
				<tr>
					<th scope="col">Nom</th>
					<th scope="col">Date de création</th>
					<th scope="col">Logo</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for brand in brands %}
					<tr>
						<td>{{ brand.name }}</td>
						<td>{{ brand.createdAt|date("d/m/Y") }}</td>
						{% if (brand.logo is not null) %}
							<td>       
								<img src="{{ asset('uploads/' ~ brand.logo) }}" width="70" alt="{{ brand.name }}">         
							</td>
						{% else  %}
							<td>       
								<p>Aucun logo</p>         
							</td>
						{% endif %}
						<td>
							<a href="{{ path('app_brand', {'id': brand.id}) }}">Afficher</a>
						</td>
						<td>
							<a href="{{ path('delete_brand', {'id': brand.id}) }}">Supprimer</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
        {% else %}
            <hr>
            <p class="text-center" >Aucune marque à afficher. </p>
            <hr>
        {% endif %}
	</section>

    <hr class="my-4">

    {# Add form for the brands #}
    <section class="add-form my-4">
        <div class="row d-flex justify-content-center">
            <div class="col-12 border p-3 rounded">
                <h2 class="text-center" style="font-size:24px;">Créer une marque</h2>
                {# Add form #}
                {{ form(add_form) }}    
            </div>
        </div>
    </section>

{% endblock %}